# Generated by Django 2.2.11 on 2020-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200321_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
